name:
    PuzzleSolver

channels:
    - conda-forge
    - pytorch
    - pytorch-test
    - pytorch-nightly

dependencies:
    - python=3.9
    - ipykernel
    - numpy
    - pip
    - scikit-learn
    - opencv
    - matplotlib
    - pytorch
    - torchvision
    - pytorch-lightning
    - optuna
    - toml
    - pip:
          - ray
          - mlflow
