name: conda-env
channels:
    - conda-forge
dependencies:
    - python
    - pytorch-lightning
    - torchvision
    - opencv
    - jupyterlab
    - ipykernel
    - optuna
    - toml
    - pandas
    - matplotlib

