name:
    PuzzleSolver

channels:
    - conda-forge
    - pytorch
    - pytorch-test
    - pytorch-nightly

dependencies:
    - python=3.8
    - tensorbaord
    - ipykernel
    - numpy
    - pip
    - scikit-learn
    - opencv
    - matplotlib
    - torchvision
    - pytorch-lightning
    - optuna
    - toml
