num_trials = 1
num_epochs = 20
gpus_per_trial = 1
cpus_per_trial = 4
num_workers = 4
raw_data_dir = '/home/hpc/iwi5/iwi5012h/dev/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv'
result_dir = '/home/hpc/iwi5/iwi5012h/ray_output'
figures_dir = '/home/hpc/iwi5/iwi5012h/figure_output'
#raw_data_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv'
#result_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results'
#figures_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/figures'

[Scheduler]
    type = 'ASHAScheduler'
    grace_period= 1
    reduction_factor = 2


