center_crop = 16
gpus = 0
batch_size = 8
num_workers = 6
save_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/logs/'
default_root_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/checkpoints/'
train_file = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/dev_train.csv'
val_file = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/dev_val.csv'
raw_img_path = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver'
min_epochs = 1
max_epochs = 2
progress_bar_refresh_rate=0.5
learning_rate = 0.001
margin = 0.9
partial_conf=1