num_trials = 1
num_epochs = 100
gpus_per_trial = 0
cpus_per_trial = 16
num_workers = 16
raw_data_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/data/hisfrag20/prepared/paris_as_csv/'
result_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/ray_results'
figures_dir = '/Users/beantown/PycharmProjects/jigsaw-puzzle-solver/results/figures/'

[Scheduler]
    type = 'ASHAScheduler'
    grace_period= 1
    reduction_factor = 2
