[lr]
type = "loguniform"
lower = 1e-4
upper = 1e-2

[batch_size]
type = "choice"
categories = [8]

[binary_margin]
type = "choice"
categories = [1.0,0.8,0.9]

[activation]
type = "choice"
categories = ['Relu','Selu']